FROM php:8.2-apache

# Enable rewrite module
RUN a2enmod rewrite

# Install MySQL support
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copy project
COPY onlineauction/ /var/www/html/

# Set permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80